CREATE TABLE IF NOT EXISTS works (
  id TEXT PRIMARY KEY,
  registration_id TEXT UNIQUE NOT NULL,
  race_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  problem_statement TEXT NOT NULL DEFAULT '',
  solution_summary TEXT NOT NULL DEFAULT '',
  tech_stack TEXT NOT NULL DEFAULT '',
  repo_url TEXT,
  demo_url TEXT,
  video_url TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  visibility TEXT NOT NULL DEFAULT 'private',
  submitted_at TEXT,
  locked_at TEXT,
  published_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (registration_id),
  UNIQUE (slug)
);
